name: Main
on: 
  push: 
    branches:
    - main
    - public
  pull_request:
    branches:
    - main
    - public
  workflow_dispatch:
jobs:
  web-deploy:
    name: Wdrażanie
    runs-on: ubuntu-latest
    steps:
    - name: Akcja Github
      uses: actions/checkout@v3

    - name: Synchronizacja plików
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with: 
        server: 74.235.160.189
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_password}}
